# Generated by Django 5.1.3 on 2024-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='manager', max_length=10),
        ),
    ]
