# Generated by Django 5.1.3 on 2024-11-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/', null=True, blank=True),
        ),
    ]


