# Generated by Django 5.1.3 on 2024-12-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=10),
        ),
    ]
