# Generated by Django 5.1.3 on 2024-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_task_assigned_teams_delete_projectteam'),
        ('users', '0006_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_projects',
            field=models.ManyToManyField(related_name='members', to='projects.project'),
        ),
    ]
