# Generated by Django 5.1.3 on 2024-11-30 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('teal', 'Teal'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('grey', 'Grey'), ('dark_purple', 'Dark Purple'), ('dark_blue', 'Dark Blue'), ('dark_green', 'Dark Green'), ('dark_teal', 'Dark Teal'), ('dark_yellow', 'Dark Yellow'), ('dark_orange', 'Dark Orange'), ('dark_grey', 'Dark Grey')], default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='emoji_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
