# Generated by Django 5.1.3 on 2024-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_color_alter_project_emoji_icon_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('amber', 'Amber'), ('blue', 'Blue'), ('green', 'Green'), ('teal', 'Teal'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Grey')], default='blue', max_length=20),
        ),
    ]
