# Generated by Django 5.1.3 on 2024-12-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_task_assigned_members_projectteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_sprint', to='projects.sprint'),
        ),
    ]
