# Generated by Django 5.1.3 on 2024-12-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_current_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
