# Generated by Django 5.1.3 on 2024-12-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_end_date_remove_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('teal', 'Teal'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Grey')], default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='emoji_icon',
            field=models.CharField(default='fa-star', max_length=255),
        ),
    ]
