# Generated by Django 5.1.3 on 2024-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_sprint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
